[package]
name = "subtitle_tonemap"
version = "1.0.0"
authors = ["quietvoid"]
edition = "2021"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.4", features = ["derive", "wrap_help", "deprecated"] }
image = "0.24.6"
rayon = "1.7.0"
